volumes:
  mongodb-data:
  postgres-data:

networks:
  dev:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - './frontend:/usr/share/nginx/html'
      - './nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - dev
  bot:
    build:
      context: ./payment_bot
    depends_on:
      - backend
    env_file:
      - .env
    networks:
      - dev
  backend:
    build:
      context: ./backend
    env_file:
      - .env  
    expose:
      - "8000"
    depends_on:
      - mongo
      - postgres
    networks:
      - dev
  mongo:
    image: mongo
    restart: always
    networks:
      - dev
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  postgres:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - dev
